{
    'name': 'IT Support Ticketing System',
    'version': '19.0.1.0.0',
    'category': 'Services/Helpdesk',
    'summary': 'IT Support Tickets with Two-Level Approval',
    'author': 'Your Company',
    'website': 'https://www.yourcompany.com',
    'depends': [
        'base',
        'hr',
        'mail',
        'portal',
        'web',
        'board',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/ticket_sequence.xml',
        'data/email_templates.xml',
        'data/ir_cron.xml',
        'data/ticket_type.xml',
        'views/it_ticket_views.xml',
        # 'views/portal_templates.xml',
        'views/reporting_by_average_time.xml',
        'views/reporting_by_category.xml',
        'views/reporting_open_tickets.xml',
        'views/reporting_solved_tickets.xml',
        'views/ticket_workflow_config_view.xml',
        'views/it_dashboard.xml',
        'data/scheduled_actions.xml',
        'views/menu_items.xml',
        'wizards/reject_wizard_views.xml',
        'wizards/approve_wizard.xml',
        'wizards/it_reminder_config_wizard.xml',
        'wizards/duration_config_wizard.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}